server:
  servlet:
    context-path: /v1
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travelagencyapplication?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: postgres
    password: myserverkonnect

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      javax.persistence.validation.mode: none
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: false

logging:
  level:
    org.springframework: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
    org.apache: WARN